---
- hosts: webservers 
  become: True
  tasks:
    - name: Install apache 2
      apt:
        name: apache2
        state: latest
    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
...
